## The program to determine whether the customer will purchase the product based on several variables below.

# The variables : all of them are features, the last row (ordered is the target)


    UserID = Id dari setiap pengunjung
    basket_icon click = Apakah pengunjung meng-klik shopping basket?
    basket_add_list = Apakah pengunjung menambahkan produk ke shopping cart pada halaman list?
    basket_add_detail = Did the visitor add a product to their shopping cart on the ‘detail’ page?
    sort_by = Did the visitor sort products on a page?
    image_picker = Did the visitor use the image picker?
    account_page_click = Did the visitor visit their account page?
    promo_banner_click = Did the visitor click on a promo banner?
    detail_wishlist_add = Did the visitor add a product to their wishlist from the ‘detail’ page?
    list_size_dropdown = Did the visitor interact with a product dropdown?
    closed_minibasket_click = Did the visitor close their mini shopping basket?
    checked_delivery_detail = Did the visitor view the delivery FAQ area on a product page?
    checked_returns_detail = Did the visitor check the returns FAQ area on a product page?
    sign_in = Did the visitor sign in to the website?
    saw_checkout = Did the visitor view the checkout?
    saw_sizecharts = Did the visitor view a product size chart?
    saw_delivery = Did the visitor view the delivery FAQ page?
    saw_account_upgrade = Did the visitor view the account upgrade page?
    saw_homepage = Did the visitor view the website homepage?
    device_mobile = Was the visitor on a mobile device?
    device_computer = Was the visitor on a desktop device?
    device_tablet = Was the visitor on a table device?
    returning_user = Was the visitor new or returning?
    loc_uk = Was the visitor located in the UK, based on their IP address?
    ordered = Did the customer place an order?

In [2]:
train_file = "training_sample.csv"
test_file = "testing_sample.csv"

In [3]:
# importing libraries  
import numpy as np
import matplotlib.pyplot as mtp  
import pandas as pd  
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import random

import warnings
warnings.filterwarnings('ignore')
#warning is imported in case F_score is divided by 0

from sklearn.preprocessing import LabelEncoder
#to convert string (Object)to numeric value) in this case, all relevant data is in numeric. Thus, this import can be removed

In [17]:
#importing datasets  
train_data= pd.read_csv(train_file)
test_data = pd.read_csv(test_file)
train_data.dtypes

UserID                     object
basket_icon_click           int64
basket_add_list             int64
basket_add_detail           int64
sort_by                     int64
image_picker                int64
account_page_click          int64
promo_banner_click          int64
detail_wishlist_add         int64
list_size_dropdown          int64
closed_minibasket_click     int64
checked_delivery_detail     int64
checked_returns_detail      int64
sign_in                     int64
saw_checkout                int64
saw_sizecharts              int64
saw_delivery                int64
saw_account_upgrade         int64
saw_homepage                int64
device_mobile               int64
device_computer             int64
device_tablet               int64
returning_user              int64
loc_uk                      int64
ordered                     int64
dtype: object

In [ ]:
#all columns has int data type besides the first column which is user ID
#which is not relavent data. So, we can remove that column and don't need
#to convert data to int

In [5]:
train_data.shape

(455401, 25)

In [38]:
test_data.shape

(151655, 25)

In [20]:
train_data.dtypes

UserID                     object
basket_icon_click           int64
basket_add_list             int64
basket_add_detail           int64
sort_by                     int64
image_picker                int64
account_page_click          int64
promo_banner_click          int64
detail_wishlist_add         int64
list_size_dropdown          int64
closed_minibasket_click     int64
checked_delivery_detail     int64
checked_returns_detail      int64
sign_in                     int64
saw_checkout                int64
saw_sizecharts              int64
saw_delivery                int64
saw_account_upgrade         int64
saw_homepage                int64
device_mobile               int64
device_computer             int64
device_tablet               int64
returning_user              int64
loc_uk                      int64
ordered                     int64
dtype: object

In [21]:
#As show above, all columns have int data type besides the first column
#which is a user ID, thus it is not relavant data to train
#We can remove that data.
#Therefore, this data set, we don't need to convert any "Obect" or"String"
#to int data type

In [22]:
#remove the first column and the last column(target)

In [23]:
feature_col = list(range(1,train_data.shape[1]-1))
feature_col

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23]

In [24]:
#self implementation
def display_data(data, chose_col_list):
    return data.iloc[:, chose_col_list]
features = display_data(train_data,feature_col)

print("The features are : \n")
features

The features are :

,basket_icon_click,basket_add_list,basket_add_detail,sort_by,image_picker,account_page_click,promo_banner_click,detail_wishlist_add,list_size_dropdown,closed_minibasket_click,...,saw_checkout,saw_sizecharts,saw_delivery,saw_account_upgrade,saw_homepage,device_mobile,device_computer,device_tablet,returning_user,loc_uk
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
4,0,1,0,1,0,0,0,0,1,0,...,1,0,0,0,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455396,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,1
455397,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
455398,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,1
455399,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
455400,1,1,1,0,0,0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1

In [25]:


features2 = display_data(test_data,feature_col)

print("The features2 are : \n")
features2

The features2 are :

,basket_icon_click,basket_add_list,basket_add_detail,sort_by,image_picker,account_page_click,promo_banner_click,detail_wishlist_add,list_size_dropdown,closed_minibasket_click,...,saw_checkout,saw_sizecharts,saw_delivery,saw_account_upgrade,saw_homepage,device_mobile,device_computer,device_tablet,returning_user,loc_uk
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151650,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,1,1
151651,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
151652,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
151653,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,1
151654,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,1,0,1

In [26]:
#feature size
features.shape

(455401, 23)

In [27]:
print("The sampe size is ", features.shape[0])

The sampe size is  455401

In [28]:
print("The attribute size is ", features.shape[1])

The attribute size is  23

In [29]:
label_index = train_data.shape[1]-1
label = display_data(train_data,[label_index ])

print("The label column is : \n")
label

The label column is :

        ordered
0             0
1             0
2             0
3             0
4             1
...         ...
455396        0
455397        0
455398        0
455399        0
455400        0

[455401 rows x 1 columns]

In [30]:
label_index = test_data.shape[1]-1
label2 = display_data(test_data,[label_index ])

print("The label2 column is : \n")
label2

The label2 column is :

        ordered
0             0
1             0
2             0
3             0
4             0
...         ...
151650        0
151651        0
151652        0
151653        0
151654        0

[151655 rows x 1 columns]

In [31]:
#Extracting Independent and dependent Variable  

# random.shuffle(train_data)
# random.shuffle(test_data)



x_train = features.values

y_train = label.values  

x_test = features2.values 

y_test = label2.values 


  
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
# x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)  
  
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()  
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

In [32]:
x_train
x_train.shape

(455401, 23)

In [33]:
x_test
x_test.shape

(151655, 23)

In [34]:
#Fitting Decision Tree classifier to the training set  
from sklearn.tree import DecisionTreeClassifier 
#classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier =DecisionTreeClassifier(criterion = "entropy", random_state = 100,max_depth = 3, min_samples_leaf = 5)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       random_state=100)

In [35]:
#Predicting the test set result  
y_pred= classifier.predict(x_test)
y_pred.shape

(151655,)

In [36]:
y_test
y_test.shape

(151655, 1)

# Training data in different models and put together model, predict, validate data, and compare with other models.

In [37]:
#self implemeantion these training functions
def train_with_entropy_generic():
    classifier= DecisionTreeClassifier(criterion='entropy', random_state=100)
    classifier.fit(x_train, y_train) 
    return classifier

In [38]:
def train_with_entropy_specific(m, min_l):
    classifier =DecisionTreeClassifier(criterion = "entropy", random_state = 100,max_depth=m, min_samples_leaf =min_l)
    classifier.fit(x_train, y_train) 
    return classifier

In [39]:
def train_with_gini_generic():
    classifier= DecisionTreeClassifier(criterion='gini', random_state=100)
    classifier.fit(x_train, y_train) 
    return classifier

In [40]:
def train_with_gini_specific(m, min_l):
    classifier =DecisionTreeClassifier(criterion = "gini", random_state = 100,max_depth=m , min_samples_leaf=min_l)
    classifier.fit(x_train, y_train) 
    return classifier

In [41]:
#self implementation
def matric_translate(confuse_matrix):
    incorrect_pred = cm[0,1]+cm[1,0]
    correct_pred = cm[0,0]+cm[1,1]
    print("Incorrect prediction number is ",incorrect_pred)
    print("Correct prediction number is ", correct_pred)

In [42]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  
print("Matric ",cm)

Matric  [[150473   1182]
 [     0      0]]

In [43]:
#self putting together
def run(model):

    
    #train generic entropy
    y_pred = model.predict(x_test)

    #Creating the Confusion matrix  

    cm= confusion_matrix(y_test, y_pred)  
    print("Confusion matrix ")
    print(cm)

    matric_translate(cm)
    print ("Accuracy : ",accuracy_score(y_test,y_pred)*100)
    print("Report : ",classification_report(y_test, y_pred))

In [44]:
print("\nModel 1 : generic entropy training \n********************************")
generic_entrop =train_with_entropy_generic()
run(generic_entrop)

Model 1 : generic entropy training
********************************
Confusion matrix
[[150603   1052]
 [     0      0]]
Incorrect prediction number is  1182
Correct prediction number is  150473
Accuracy :  99.30632026639412
Report :                precision    recall  f1-score   support

           0       1.00      0.99      1.00    151655
           1       0.00      0.00      0.00         0

    accuracy                           0.99    151655
   macro avg       0.50      0.50      0.50    151655
weighted avg       1.00      0.99      1.00    151655

In [45]:
print("\nModel 2 : specific entropy training with max depth is 5 and 3 as min of leaves.\n********************************")

specific_entrop = train_with_entropy_specific(5, 3)

run(specific_entrop)

Model 2 : specific entropy training with max depth is 5 and 3 as min of leaves.
********************************
Confusion matrix
[[150533   1122]
 [     0      0]]
Incorrect prediction number is  1182
Correct prediction number is  150473
Accuracy :  99.26016286967129
Report :                precision    recall  f1-score   support

           0       1.00      0.99      1.00    151655
           1       0.00      0.00      0.00         0

    accuracy                           0.99    151655
   macro avg       0.50      0.50      0.50    151655
weighted avg       1.00      0.99      1.00    151655

In [46]:
print("\nModel 3 : specific entropy training with max depth is 7 and 3 as min of leaves.\n********************************")



specific_entrop2 = train_with_entropy_specific(7, 3)
run(specific_entrop2)

Model 3 : specific entropy training with max depth is 7 and 3 as min of leaves.
********************************
Confusion matrix
[[150527   1128]
 [     0      0]]
Incorrect prediction number is  1182
Correct prediction number is  150473
Accuracy :  99.25620652138076
Report :                precision    recall  f1-score   support

           0       1.00      0.99      1.00    151655
           1       0.00      0.00      0.00         0

    accuracy                           0.99    151655
   macro avg       0.50      0.50      0.50    151655
weighted avg       1.00      0.99      1.00    151655

In [47]:
print("\nModel 4  : specific entropy training with max depth is 2 and 2 as min of leaves.\n********************************")



specific_entrop2 = train_with_entropy_specific(2, 2)
run(specific_entrop2)

Model 4  : specific entropy training with max depth is 2 and 2 as min of leaves.
********************************
Confusion matrix
[[150473   1182]
 [     0      0]]
Incorrect prediction number is  1182
Correct prediction number is  150473
Accuracy :  99.22059938676601
Report :                precision    recall  f1-score   support

           0       1.00      0.99      1.00    151655
           1       0.00      0.00      0.00         0

    accuracy                           0.99    151655
   macro avg       0.50      0.50      0.50    151655
weighted avg       1.00      0.99      1.00    151655

In [48]:
print("\nModel 5 : generic gini training\n********************************")

generic_gini = train_with_gini_generic()

run(generic_gini)

Model 5 : generic gini training
********************************
Confusion matrix
[[150605   1050]
 [     0      0]]
Incorrect prediction number is  1182
Correct prediction number is  150473
Accuracy :  99.30763904915763
Report :                precision    recall  f1-score   support

           0       1.00      0.99      1.00    151655
           1       0.00      0.00      0.00         0

    accuracy                           0.99    151655
   macro avg       0.50      0.50      0.50    151655
weighted avg       1.00      0.99      1.00    151655

In [49]:
print("\nModel 6 : specific gini training with 5 max depth and 3 min leaves\n********************************")

specific_gini = train_with_gini_specific(5,3)


run(specific_gini)

Model 6 : specific gini training with 5 max depth and 3 min leaves
********************************
Confusion matrix
[[150533   1122]
 [     0      0]]
Incorrect prediction number is  1182
Correct prediction number is  150473
Accuracy :  99.26016286967129
Report :                precision    recall  f1-score   support

           0       1.00      0.99      1.00    151655
           1       0.00      0.00      0.00         0

    accuracy                           0.99    151655
   macro avg       0.50      0.50      0.50    151655
weighted avg       1.00      0.99      1.00    151655

In [50]:
print("\nModel 7 : specific gini training with 7 max depth and 3 min leaves\n********************************")

specific_gini2 = train_with_gini_specific(7,3)


run(specific_gini2)

Model 7 : specific gini training with 7 max depth and 3 min leaves
********************************
Confusion matrix
[[150527   1128]
 [     0      0]]
Incorrect prediction number is  1182
Correct prediction number is  150473
Accuracy :  99.25620652138076
Report :                precision    recall  f1-score   support

           0       1.00      0.99      1.00    151655
           1       0.00      0.00      0.00         0

    accuracy                           0.99    151655
   macro avg       0.50      0.50      0.50    151655
weighted avg       1.00      0.99      1.00    151655

In [51]:
print("\nModel 8 : specific gini training with None max depth and 2 min leaves\n********************************")

specific_gini3 = train_with_gini_specific(2,2)


run(specific_gini3)

Model 8 : specific gini training with None max depth and 2 min leaves
********************************
Confusion matrix
[[150473   1182]
 [     0      0]]
Incorrect prediction number is  1182
Correct prediction number is  150473
Accuracy :  99.22059938676601
Report :                precision    recall  f1-score   support

           0       1.00      0.99      1.00    151655
           1       0.00      0.00      0.00         0

    accuracy                           0.99    151655
   macro avg       0.50      0.50      0.50    151655
weighted avg       1.00      0.99      1.00    151655

https://www.kaggle.com/benpowis/customer-propensity-to-purchase/data

Sources : Part of codes : https://www.javatpoint.com/machine-learning-decision-tree-classification-algorithm

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html